/**
 * Realistic Mock Data Fixtures according to PRD & Technical Spec
 * Allows Developer 2 to build full UI workflows offline before backend integration
 */

export const mockDepartments = [
  { id: 'dept-eng', name: 'Engineering', code: 'ENG', employeeCount: 14 },
  { id: 'dept-prod', name: 'Product Management', code: 'PROD', employeeCount: 4 },
  { id: 'dept-hr', name: 'People & Culture', code: 'HR', employeeCount: 3 },
  { id: 'dept-fin', name: 'Finance & Payroll', code: 'FIN', employeeCount: 3 },
];

export const mockEmployees = [
  {
    id: 'emp-john-1',
    employeeCode: 'EMP-001',
    firstName: 'John',
    lastName: 'Developer',
    email: 'employee@peoplepay.com',
    jobTitle: 'Senior Full Stack Engineer',
    departmentId: 'dept-eng',
    department: 'Engineering',
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    hireDate: '2023-01-15',
    activeContractId: 'cnt-john-1',
    workingScheduleId: 'sch-1',
    scheduleName: 'Standard Full-Time (40h)',
    phone: '+1 (555) 019-2834',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-alex-1',
    employeeCode: 'EMP-002',
    firstName: 'Alex',
    lastName: 'Rivera',
    email: 'alex.rivera@peoplepay360.com',
    jobTitle: 'Staff Software Engineer',
    departmentId: 'dept-eng',
    department: 'Engineering',
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    hireDate: '2023-03-15',
    activeContractId: 'cnt-1',
    workingScheduleId: 'sch-1',
    scheduleName: 'Standard Full-Time (40h)',
    phone: '+1 (555) 012-3456',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-sarah-1',
    employeeCode: 'EMP-003',
    firstName: 'Sarah',
    lastName: 'Connor',
    email: 'sarah.payroll@peoplepay360.com',
    jobTitle: 'Payroll Lead',
    departmentId: 'dept-fin',
    department: 'Finance & Payroll',
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    hireDate: '2022-01-10',
    activeContractId: 'cnt-2',
    workingScheduleId: 'sch-1',
    scheduleName: 'Standard Full-Time (40h)',
    phone: '+1 (555) 014-9988',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-marcus-1',
    employeeCode: 'EMP-004',
    firstName: 'Marcus',
    lastName: 'Vance',
    email: 'marcus.v@peoplepay360.com',
    jobTitle: 'Senior UI/UX Designer',
    departmentId: 'dept-prod',
    department: 'Product Management',
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    hireDate: '2024-02-01',
    activeContractId: 'cnt-3',
    workingScheduleId: 'sch-1',
    scheduleName: 'Standard Full-Time (40h)',
    phone: '+1 (555) 017-8822',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-jane-1',
    employeeCode: 'EMP-005',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@peoplepay360.com',
    jobTitle: 'HR Director',
    departmentId: 'dept-hr',
    department: 'People & Culture',
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    hireDate: '2022-04-12',
    activeContractId: 'cnt-4',
    workingScheduleId: 'sch-1',
    scheduleName: 'Standard Full-Time (40h)',
    phone: '+1 (555) 018-3344',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-charlie-1',
    employeeCode: 'EMP-006',
    firstName: 'Charlie',
    lastName: 'Finance',
    email: 'charlie.f@peoplepay360.com',
    jobTitle: 'Senior Financial Analyst',
    departmentId: 'dept-fin',
    department: 'Finance & Payroll',
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    hireDate: '2023-08-01',
    activeContractId: 'cnt-5',
    workingScheduleId: 'sch-1',
    scheduleName: 'Standard Full-Time (40h)',
    phone: '+1 (555) 019-4455',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-elena-1',
    employeeCode: 'EMP-007',
    firstName: 'Elena',
    lastName: 'Rostova',
    email: 'elena.rostova@peoplepay360.com',
    jobTitle: 'Lead Backend Engineer',
    departmentId: 'dept-eng',
    department: 'Engineering',
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    hireDate: '2023-05-10',
    activeContractId: 'cnt-6',
    workingScheduleId: 'sch-1',
    scheduleName: 'Standard Full-Time (40h)',
    phone: '+1 (555) 020-5566',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-david-1',
    employeeCode: 'EMP-008',
    firstName: 'David',
    lastName: 'Kim',
    email: 'david.kim@peoplepay360.com',
    jobTitle: 'Cloud & DevOps Architect',
    departmentId: 'dept-eng',
    department: 'Engineering',
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    hireDate: '2023-09-15',
    activeContractId: 'cnt-7',
    workingScheduleId: 'sch-1',
    scheduleName: 'Standard Full-Time (40h)',
    phone: '+1 (555) 021-6677',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-priya-1',
    employeeCode: 'EMP-009',
    firstName: 'Priya',
    lastName: 'Patel',
    email: 'priya.patel@peoplepay360.com',
    jobTitle: 'Senior Frontend Engineer',
    departmentId: 'dept-eng',
    department: 'Engineering',
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    hireDate: '2023-11-20',
    activeContractId: 'cnt-8',
    workingScheduleId: 'sch-1',
    scheduleName: 'Standard Full-Time (40h)',
    phone: '+1 (555) 022-7788',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-james-1',
    employeeCode: 'EMP-010',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'james.wilson@peoplepay360.com',
    jobTitle: 'Principal Product Manager',
    departmentId: 'dept-prod',
    department: 'Product Management',
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    hireDate: '2022-09-01',
    activeContractId: 'cnt-9',
    workingScheduleId: 'sch-1',
    scheduleName: 'Standard Full-Time (40h)',
    phone: '+1 (555) 023-8899',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-maria-1',
    employeeCode: 'EMP-011',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'maria.garcia@peoplepay360.com',
    jobTitle: 'Talent Acquisition Specialist',
    departmentId: 'dept-hr',
    department: 'People & Culture',
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    hireDate: '2024-01-10',
    activeContractId: 'cnt-10',
    workingScheduleId: 'sch-1',
    scheduleName: 'Standard Full-Time (40h)',
    phone: '+1 (555) 024-9900',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-lucas-1',
    employeeCode: 'EMP-012',
    firstName: 'Lucas',
    lastName: 'Vance',
    email: 'lucas.vance@peoplepay360.com',
    jobTitle: 'QA Automation Engineer',
    departmentId: 'dept-eng',
    department: 'Engineering',
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    hireDate: '2024-03-01',
    activeContractId: 'cnt-11',
    workingScheduleId: 'sch-1',
    scheduleName: 'Standard Full-Time (40h)',
    phone: '+1 (555) 025-1122',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-emily-1',
    employeeCode: 'EMP-013',
    firstName: 'Emily',
    lastName: 'Watson',
    email: 'emily.watson@peoplepay360.com',
    jobTitle: 'Payroll Specialist',
    departmentId: 'dept-fin',
    department: 'Finance & Payroll',
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    hireDate: '2024-04-15',
    activeContractId: 'cnt-12',
    workingScheduleId: 'sch-1',
    scheduleName: 'Standard Full-Time (40h)',
    phone: '+1 (555) 026-2233',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-robert-1',
    employeeCode: 'EMP-014',
    firstName: 'Robert',
    lastName: 'Taylor',
    email: 'robert.taylor@peoplepay360.com',
    jobTitle: 'UX Researcher',
    departmentId: 'dept-prod',
    department: 'Product Management',
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    hireDate: '2023-07-22',
    activeContractId: 'cnt-13',
    workingScheduleId: 'sch-1',
    scheduleName: 'Standard Full-Time (40h)',
    phone: '+1 (555) 027-3344',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'emp-aisha-1',
    employeeCode: 'EMP-015',
    firstName: 'Aisha',
    lastName: 'Khan',
    email: 'aisha.khan@peoplepay360.com',
    jobTitle: 'Mobile App Engineer',
    departmentId: 'dept-eng',
    department: 'Engineering',
    employmentType: 'FULL_TIME',
    status: 'ACTIVE',
    hireDate: '2024-05-01',
    activeContractId: 'cnt-14',
    workingScheduleId: 'sch-1',
    scheduleName: 'Standard Full-Time (40h)',
    phone: '+1 (555) 028-4455',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
];

export const mockWorkingSchedules = [
  {
    id: 'sch-1',
    name: '40 Hours / Week',
    company: 'My Company',
    timezone: 'Company timezone',
    daysPerWeek: 5,
    hoursPerWeek: '40h',
    calculatedWeeklyHours: 40,
    status: 'Active',
    workDays: [
      { day: 'Monday', isWorkDay: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 },
      { day: 'Tuesday', isWorkDay: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 },
      { day: 'Wednesday', isWorkDay: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 },
      { day: 'Thursday', isWorkDay: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 },
      { day: 'Friday', isWorkDay: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 },
    ],
  },
  {
    id: 'sch-2',
    name: 'Night Shift',
    company: 'My Company',
    timezone: 'Company timezone',
    daysPerWeek: 5,
    hoursPerWeek: '40h',
    calculatedWeeklyHours: 40,
    status: 'Active',
    workDays: [
      { day: 'Monday', isWorkDay: true, startTime: '22:00', endTime: '07:00', breakMinutes: 60 },
      { day: 'Tuesday', isWorkDay: true, startTime: '22:00', endTime: '07:00', breakMinutes: 60 },
      { day: 'Wednesday', isWorkDay: true, startTime: '22:00', endTime: '07:00', breakMinutes: 60 },
      { day: 'Thursday', isWorkDay: true, startTime: '22:00', endTime: '07:00', breakMinutes: 60 },
      { day: 'Friday', isWorkDay: true, startTime: '22:00', endTime: '07:00', breakMinutes: 60 },
    ],
  },
  {
    id: 'sch-3',
    name: 'Retail Weekend',
    company: 'My Company',
    timezone: 'Company timezone',
    daysPerWeek: 5,
    hoursPerWeek: '40h',
    calculatedWeeklyHours: 40,
    status: 'Active',
    workDays: [
      { day: 'Wednesday', isWorkDay: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 },
      { day: 'Thursday', isWorkDay: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 },
      { day: 'Friday', isWorkDay: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 },
      { day: 'Saturday', isWorkDay: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 },
      { day: 'Sunday', isWorkDay: true, startTime: '09:00', endTime: '18:00', breakMinutes: 60 },
    ],
  },
  {
    id: 'sch-4',
    name: 'Flexible Hybrid',
    company: 'My Company',
    timezone: 'Company timezone',
    daysPerWeek: 5,
    hoursPerWeek: '37.5h',
    calculatedWeeklyHours: 37.5,
    status: 'Active',
    workDays: [
      { day: 'Monday', isWorkDay: true, startTime: '09:30', endTime: '17:30', breakMinutes: 30 },
      { day: 'Tuesday', isWorkDay: true, startTime: '09:30', endTime: '17:30', breakMinutes: 30 },
      { day: 'Wednesday', isWorkDay: true, startTime: '09:30', endTime: '17:30', breakMinutes: 30 },
      { day: 'Thursday', isWorkDay: true, startTime: '09:30', endTime: '17:30', breakMinutes: 30 },
      { day: 'Friday', isWorkDay: true, startTime: '09:30', endTime: '17:30', breakMinutes: 30 },
    ],
  },
  {
    id: 'sch-5',
    name: 'Part-time 20h',
    company: 'My Company',
    timezone: 'Company timezone',
    daysPerWeek: 4,
    hoursPerWeek: '20h',
    calculatedWeeklyHours: 20,
    status: 'Inactive',
    workDays: [
      { day: 'Monday', isWorkDay: true, startTime: '09:00', endTime: '14:00', breakMinutes: 0 },
      { day: 'Tuesday', isWorkDay: true, startTime: '09:00', endTime: '14:00', breakMinutes: 0 },
      { day: 'Wednesday', isWorkDay: true, startTime: '09:00', endTime: '14:00', breakMinutes: 0 },
      { day: 'Thursday', isWorkDay: true, startTime: '09:00', endTime: '14:00', breakMinutes: 0 },
    ],
  },
];

export const mockContracts = [
  {
    id: 'cnt-john-1',
    contractCode: 'CNT-2024-001',
    employeeId: 'emp-john-1',
    employeeName: 'John Developer',
    employeeCode: 'emp-john-1',
    department: 'Engineering',
    jobPosition: 'Senior Full Stack Engineer',
    wage: 8500,
    wageType: 'MONTHLY',
    workingSchedule: '40 Hours / Week',
    startDate: '2024-01-01',
    endDate: null,
    status: 'ACTIVE',
    salaryStructureName: 'Standard Executive Structure',
    notes: 'This running contract is the source for payroll calculation in the active period.',
  },
  {
    id: 'cnt-1',
    contractCode: 'CNT-2024-002',
    employeeId: 'emp-alex-1',
    employeeName: 'Alex Rivera',
    employeeCode: 'EMP-002',
    department: 'Engineering',
    jobPosition: 'Staff Software Engineer',
    wage: 8500,
    wageType: 'MONTHLY',
    workingSchedule: '40 Hours / Week',
    startDate: '2024-01-01',
    endDate: null,
    status: 'ACTIVE',
    salaryStructureName: 'Standard Executive Structure',
    notes: 'This running contract is the source for payroll calculation in the active period.',
  },
  {
    id: 'cnt-jane-1',
    contractCode: 'CNT-A670A4',
    employeeId: 'emp-jane-1',
    employeeName: 'Jane HR Specialist',
    employeeCode: 'EMP002',
    department: 'People & Culture',
    jobPosition: 'HR Specialist',
    wage: 8500,
    wageType: 'MONTHLY',
    workingSchedule: '40 Hours / Week',
    startDate: '2026-01-01',
    endDate: null,
    status: 'ACTIVE',
    salaryStructureName: 'Standard Executive Structure',
    notes: 'This running contract is the source for payroll calculation in the active period.',
  },
  {
    id: 'cnt-fhgkjj-1',
    contractCode: 'CON/2026/0043',
    employeeId: 'emp-fhgkjj-1',
    employeeName: 'fhgkjj fjb',
    employeeCode: 'EMP-516',
    department: 'Finance',
    jobPosition: 'Software Engineer',
    wage: 85000,
    wageType: 'MONTHLY',
    workingSchedule: '40 Hours / Week',
    startDate: '2026-01-09',
    endDate: '2026-09-17',
    status: 'ACTIVE',
    salaryStructureName: 'Standard Executive Structure',
    notes: 'This running contract is the source for payroll calculation in the active period.',
  },
  {
    id: 'cnt-asdf-1',
    contractCode: 'CON/2026/0044',
    employeeId: 'emp-asdf-1',
    employeeName: 'asdf fdas',
    employeeCode: 'EMP-519',
    department: 'Finance',
    jobPosition: 'Software',
    wage: 85000,
    wageType: 'MONTHLY',
    workingSchedule: '40 Hours / Week',
    startDate: '2026-01-01',
    endDate: '2026-09-30',
    status: 'ACTIVE',
    salaryStructureName: 'Standard Executive Structure',
    notes: 'This running contract is the source for payroll calculation in the active period.',
  },
  {
    id: 'cnt-john-dev-1',
    contractCode: 'CNT-A670A3',
    employeeId: 'emp-john-1',
    employeeName: 'John Developer',
    employeeCode: 'EMP001',
    department: 'Engineering',
    jobPosition: 'Senior Full Stack Engineer',
    wage: 10000,
    wageType: 'MONTHLY',
    workingSchedule: '40 Hours / Week',
    startDate: '2026-01-01',
    endDate: null,
    status: 'ACTIVE',
    salaryStructureName: 'Standard Executive Structure',
    notes: 'This running contract is the source for payroll calculation in the active period.',
  },
  {
    id: 'cnt-charlie-1',
    contractCode: 'CNT-A670A5',
    employeeId: 'emp-charlie-1',
    employeeName: 'Charlie Finance',
    employeeCode: 'EMP003',
    department: 'Finance',
    jobPosition: 'Payroll Administrator',
    wage: 9000,
    wageType: 'MONTHLY',
    workingSchedule: '40 Hours / Week',
    startDate: '2026-01-01',
    endDate: null,
    status: 'ACTIVE',
    salaryStructureName: 'Standard Executive Structure',
    notes: 'This running contract is the source for payroll calculation in the active period.',
  },
  {
    id: 'cnt-john-exp-1',
    contractCode: 'CNT-A670A1',
    employeeId: 'emp-john-1',
    employeeName: 'John Developer',
    employeeCode: 'EMP001',
    department: 'Engineering',
    jobPosition: 'Junior Engineer',
    wage: 6000,
    wageType: 'MONTHLY',
    workingSchedule: '40 Hours / Week',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'EXPIRED',
    isPrior: true,
    salaryStructureName: 'Standard Executive Structure',
    notes: 'Previous fixed term contract expired.',
  },
  {
    id: 'cnt-john-dev-2',
    contractCode: 'CNT-A670A3',
    employeeId: 'emp-john-1',
    employeeName: 'John Developer',
    employeeCode: 'EMP001',
    department: 'Engineering',
    jobPosition: 'Senior Full Stack Engineer',
    wage: 10000,
    wageType: 'MONTHLY',
    workingSchedule: '40 Hours / Week',
    startDate: '2026-01-01',
    endDate: null,
    status: 'ACTIVE',
    salaryStructureName: 'Standard Executive Structure',
    notes: 'This running contract is the source for payroll calculation in the active period.',
  },
  {
    id: 'cnt-charlie-2',
    contractCode: 'CNT-A670A5',
    employeeId: 'emp-charlie-1',
    employeeName: 'Charlie Finance',
    employeeCode: 'EMP003',
    department: 'Finance & Payroll',
    jobPosition: 'Financial Analyst',
    wage: 9000,
    wageType: 'MONTHLY',
    workingSchedule: '40 Hours / Week',
    startDate: '2026-01-01',
    endDate: null,
    status: 'ACTIVE',
    salaryStructureName: 'Standard Executive Structure',
    notes: 'This running contract is the source for payroll calculation in the active period.',
  },
  {
    id: 'cnt-john-exp-2',
    contractCode: 'CNT-A670A1',
    employeeId: 'emp-john-1',
    employeeName: 'John Developer',
    employeeCode: 'EMP001',
    department: 'Engineering',
    jobPosition: 'Junior Developer',
    wage: 6000,
    wageType: 'MONTHLY',
    workingSchedule: '40 Hours / Week',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'EXPIRED',
    isPrior: true,
    salaryStructureName: 'Standard Executive Structure',
    notes: 'Previous fixed term contract expired.',
  },
  {
    id: 'cnt-aarav-1',
    contractCode: 'CON/2026/0042',
    employeeId: 'emp-aarav-1',
    employeeName: 'Aarav Mehta',
    employeeCode: 'EMP-042',
    department: 'Finance',
    jobPosition: 'Payroll Specialist',
    wage: 85000,
    wageType: 'MONTHLY',
    workingSchedule: '40 Hours / Week',
    startDate: '2026-01-01',
    endDate: null,
    status: 'ACTIVE',
    salaryStructureName: 'Standard Executive Structure',
    notes: 'This running contract is the source for payroll calculation in the active period.',
  },
  {
    id: 'cnt-2',
    contractCode: 'CNT-2023-042',
    employeeId: 'emp-sarah-1',
    employeeName: 'Sarah Connor',
    employeeCode: 'EMP-003',
    department: 'Finance & Payroll',
    jobPosition: 'Payroll Lead',
    wage: 7200,
    wageType: 'MONTHLY',
    workingSchedule: '40 Hours / Week',
    startDate: '2023-06-01',
    endDate: null,
    status: 'ACTIVE',
    salaryStructureName: 'Standard Executive Structure',
    notes: 'This running contract is the source for payroll calculation in the active period.',
  },
];

export const mockPayruns = [
  {
    id: 'pr-2026-09',
    name: 'September 2026 Regular Payrun',
    periodStart: '2026-09-01',
    periodEnd: '2026-09-30',
    status: 'COMPUTED',
    salaryStructureName: 'Standard Tech Structure',
    employeeCount: 3,
    totalGross: 24200,
    totalNet: 18950,
    warningsCount: 1,
    createdAt: '2026-09-02T10:00:00Z',
  },
];

export const mockDashboardMetrics = {
  totalEmployees: 24,
  activeContracts: 23,
  payrollExpenditure: 142500,
  pendingLeaveRequests: 2,
  attendanceExceptions: 1,
  monthlyPayrollTrends: [
    { month: 'Apr', amount: 135000 },
    { month: 'May', amount: 136200 },
    { month: 'Jun', amount: 138000 },
    { month: 'Jul', amount: 140500 },
    { month: 'Aug', amount: 141000 },
    { month: 'Sep', amount: 142500 },
  ],
};
